name: Building and Testing

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Building
      run: |
        cmake -H"." -B"build"
        cmake --build "build" --target all

    - name: Run tests
      run: ./vtu11_testrunner
