name: Building and Testing

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v1

    - name: Building
      run: |
        cmake -H"." -DVTU11_ENABLE_TESTS=ON -B"build"
        cmake --build "build"

    - name: Run tests
      run: |
        cd build
        if [ -f "vtu11_testrunner" ]; then
            ./vtu11_testrunner
        fi
        if [ -f "Debug/vtu11_testrunner.exe" ]; then
            Debug/vtu11_testrunner.exe
        fi
